version: "3.9" # Updated version for better features and compatibility

services:
  app:
    build:
      context: . # Dockerfile is in the current directory
      dockerfile: Dockerfile
    container_name: cangkruan-api
    ports:
      - "9876:9876"
    volumes:
      - ./internal/configs/app.env:/app/app.env
