version: "1"

services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - "/D:/LEARN/DEVELOPMENT/mysql:/var/lib/mysql"
